name: PG-Finder-Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Create an Image
        run: docker build -t pg-finder:latest .
      - name: Create and Run the container
        run: docker run -d -p 3000:3000 pg-finder:latest
      
