name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: printing
        run: echo "Hello From Aniket"
        

  run-project:
    runs-on: ubuntu-latest
    needs: build-and-run
    steps:
      - name: print run project
        run: echo "Hello from Run Project Job"
      
      
