name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: npm install
        

  # run-project:
  #   runs-on: self-hosted
  #   needs: build-and-run
  #   steps:
      - name: run the project
        run: nohup npm run start > app.log 2>&1 &
        # run: npm run start
      
      
