name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: npm install
        

  run-project:
    runs-on: ubuntu-latest
    needs: build-and-run
    steps:
      - name: run the project
        run: npm run start
      
      
